### ISSUE TITLE
please dark and light screen mode toggle button

### ISSUE THREAD

**Issue by River-Mochi** [JakubAndrysek/MkDoxy-demo#1]
please add toggle button to your page so people who want light mode can use it thanks :)

https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle

this page for example, I could not find button on top to change to light mode. https://mkdoxy-demo.kubaandrysek.cz/

**Comment by JakubAndrysek** [comment]
Thank you for your feedback. I am a big fan of dark modes so I didn`t add them. 
It has been added to all of my repos.
